build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  environment:
    php: 7.2

filter:
  excluded_paths:
    - "tests/*"
  dependency_paths:
    - "vendor/*"
