language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: 7.1

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v
  - bash <(curl -s https://codecov.io/bash) -t 7f81cbf0-1181-488f-a659-3868a104acac
